# Build pipeline
trigger:
  batch: false
  branches:
    include:
     - dev
  paths:
    exclude:
     - readme.md
pool:
  vmImage: ubuntu-latest
steps:
 - task: NodeTool@0
   displayName: 'Use Node 18.x'
   inputs:
     versionSpec: 18.x
 - script: |
     npm install -g @angular/cli
   displayName: 'install angular cli'
 - task: Npm@1
   displayName: 'npm install '
   inputs:
     workingDir: '$(System.DefaultWorkingDirectory)'
     verbose: false
 - task: Npm@1
   displayName: 'npm build'
   inputs:
     command: custom
     workingDir: '$(System.DefaultWorkingDirectory)'
     verbose: false
     customCommand: 'run build'
 - task: AzureStaticWebApp@0
   inputs:
     app_location:  '/'
     output_location:  'dist/my-app'
     azure_static_web_apps_api_token: $(ANGULAR_TOKENS)
    
      

     
